# Generated by Django 2.1 on 2018-11-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateInf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=4)),
                ('identificationNumber', models.CharField(max_length=256)),
                ('etpName', models.CharField(max_length=256)),
                ('technicalTitle', models.CharField(max_length=256)),
                ('certificateCode', models.CharField(max_length=256)),
                ('issuingDate', models.CharField(max_length=256)),
                ('certificateValidity', models.CharField(max_length=256)),
            ],
        ),
    ]
