# Generated by Django 2.1 on 2018-11-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificateInf',
            new_name='CertificateInfo',
        ),
    ]
