# Generated by Django 2.1 on 2018-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20181116_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinfo',
            name='image_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
