# Generated by Django 2.1 on 2018-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20181116_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateinfo',
            name='certificate_validity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='issuing_date',
            field=models.DateField(),
        ),
    ]
