# Generated by Django 2.1 on 2018-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20181116_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinfo',
            name='md_5',
            field=models.CharField(default=1, editable=False, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='certificate_code',
            field=models.CharField(max_length=256, verbose_name='证书编号'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='certificate_validity',
            field=models.DateField(verbose_name='证书有效期'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='etp_name',
            field=models.CharField(max_length=256, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='gender',
            field=models.CharField(max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='identification_number',
            field=models.CharField(max_length=256, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='image_id',
            field=models.ImageField(upload_to='image', verbose_name='证件照'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='issuing_date',
            field=models.DateField(verbose_name='发证时间'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='name',
            field=models.CharField(max_length=256, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='certificateinfo',
            name='technical_title',
            field=models.CharField(max_length=256, verbose_name='职务'),
        ),
    ]
